version: '3.1'
services:
  accounting-system:
    image: accounting-system:latest
    hostname: accounting-system
    build:
      context: ./accounting-system
      dockerfile: Dockerfile
    container_name: accounting-system
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=accounting-db